### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by eps000** [allistoncarlos/homebridge-servo-switch#1]
I there anyway to modify this to make it work with a nocemcu instead of the pi? thank you

**Comment by allistoncarlos** [comment]
I'm waiting for my NodeMCU to arrive to do some tests! Hope to help you soon :)
Thanks for the support.

**Comment by eps000** [comment]
Looking forward to it!

**Comment by allistoncarlos** [comment]
@eps000 Sorry for taking too long, my NodeMCU just arrived today... Anyway, I've created an INO file to control the servo, turning it "on" and "off". If you'd like to use Homebridge, I recommend to use a specific plugin. Details on the README.md :)

**Comment by eps000** [comment]
Thank you!
